name: Test Emotion Recognition

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless numpy pillow
          pip install -r config/requirements.txt || true

      - name: Test imports
        run: |
          python -c "import cv2; print('OpenCV version:', cv2.__version__)"
          python -c "import numpy; print('NumPy version:', numpy.__version__)"
          python -c "import PIL; print('Pillow available')"

      - name: Test face detection
        run: |
          python -c "
          import cv2
          import numpy as np

          # Test face cascade loading
          cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
          print('Face cascade loaded:', not cascade.empty())

          # Test with dummy image
          dummy_img = np.zeros((480, 640, 3), dtype=np.uint8)
          gray = cv2.cvtColor(dummy_img, cv2.COLOR_BGR2GRAY)
          faces = cascade.detectMultiScale(gray)
          print('Face detection test passed')
          "

      - name: Test basic emotion detection
        run: |
          python -c "
          import sys
          import os
          sys.path.append('src/core')

          # Test basic imports without running GUI
          try:
              import numpy as np
              import cv2
              print('Basic dependencies working')
          except ImportError as e:
              print(f'Import error: {e}')
              sys.exit(1)
          "

  raspberry-pi-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Raspberry Pi dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements_raspberry_pi.txt || true
          pip install opencv-python-headless numpy pillow

      - name: Test Raspberry Pi compatibility
        run: |
          python -c "
          import sys
          sys.path.append('scripts')

          # Test Pi-specific imports
          try:
              import cv2
              import numpy as np
              from PIL import Image
              print('Raspberry Pi dependencies working')
          except ImportError as e:
              print(f'Pi dependency error: {e}')
              sys.exit(1)
          "
